---
title: Stochastic Modeling and Optimization Problemset 1
author: Aimee Barciauskas, Andreas Lloyd, Francis Thomas Moynihan IV, and Seda Yilmaz
date: 25 February 2016
output: pdf_document
---

# 1. Machine maintenance

* $x_{k}$ - (*state*) Machine is working or broken
* $u_{k}$ - (*control*) Whether to perform maintenance
* $w_{k}$ - (*uncertainty*) Machine breaks or doesn't break

There are no additional dynamics or constraints for this problem.

Expected profit is always $\$100 - g(u)$ where $g(u)$ is the exepected cost of decision $u$, (i.e.: $\mathbb{E}_{w}\{G(u,w)\}$). By minimizing expected cost we maximize expected profit.

At the beginning of each week, we much pick an optimal strategy given $x_{k}$: the machine is working or broken.

**State 1: when the machine is working,** (the initial state), we have two strategies and their associated expected costs:

**Option 1: Perform Maintenence**

If maintenance is performed, the expected cost is 20 (the cost of maintenance) plus the probability the machine breaks during the week times lost profit:

$J_{\mu_{0}} = 20 + 0.4*100 = 60$

**Option 2: Do nothing**

If maintenance is not performed, the expected cost is the probability the machine breaks down times lost profit.

$J_{\mu_{1}} = 0.7*100 = 70$

*Strategy when the machine is working, performing maintenance minimizes expected cost.*

**State 2: when the machine is broken,** there are three strategies:

**Option 1: Buy a new machine.**

$J_{\mu_{0}} = 90$

**Option 2: Repair the machine.**

$J_{\mu_{1}} = 40 + 0.4*100 = 80$

**Option 3: Do nothing.**

$J_{\mu_{2}} = 100$

*When the machine is broken, making a repair minimizes expected cost*

**The optimal strategy which minimizes expected cost (and maximizes expected profit) is to perform preventative maintenance when the machine is working and repair the machine when it is broken.**

Alternately, we can state these strategies as the policies:

$\pi = \mu_{k}(x_{k}) = u_{k}$

$\mu_{k}(working) = \text{ perform preventative maintenance}$

$\mu_{k}(broken) = \text{ repair broken machine}$

**DP Algorithm**

1. $J^{*}(x_{0}) = min_{\pi}J_{\pi}(x_{0}) =  \mu_{k}(working)$
2. From week $1,..,4$, act according to policies $\pi = {\mu(broken), \mu(working)}$, as the policies are detailed above.

# 2. Discounted Cost

**In the framework of the basic problem, consider the case where the cost is of the form:**

$$\mathbb{E}_{w_{k}}\bigg\{ \alpha^{N}g_{N}(x_{N}) + \sum_{k=0}^{N-1} \alpha^{k} g_{k}(x_{k},u_{k},w_{k}) \bigg\}$$

**where $\alpha \in (0,1)$ is a discount factor. Develop a DP-like algorithm for this problem.**

$$J_{N}(x_{N}) = \alpha^{N}g_{N}(x_{N}) <=> J_{N}(x_{N})\alpha^{-N} = g_{N}(x_{N})$$

$$J_{k}(x_{k}) = \min\limits_{u_{k}} \mathbb{E}_{w_{k}} \bigg\{ \alpha^{k} g_{k}(x_{k},u_{k},w_{k}) + J_{k+1}(f_{k}(x_{k}, u_{k},w_{k})\bigg\}$$

$$J_{k}(x_{k})\alpha^{-k} = \min\limits_{u_{k}} \mathbb{E}_{w_{k}} \bigg\{ g_{k}(x_{k},u_{k},w_{k}) + \alpha^{-k}J_{k+1}(f_{k}(x_{k}, u_{k},w_{k})\bigg\}$$

$$J_{k}(x_{k})\alpha^{-k} = \min\limits_{u_{k}} \mathbb{E}_{w_{k}} \bigg\{ g_{k}(x_{k},u_{k},w_{k}) + \alpha \alpha^{-k+1}J_{k+1}(f_{k}(x_{k}, u_{k},w_{k})\bigg\}$$

Let $\phi_{k} := J_{k}x_{k}\alpha^{-k}$, then for the DP algorithm:

**Initial step:** $\phi_{N}(x_{N}) = g_{N}(x_{N})$

**Recursive function:** $\phi_{k}(x_{k}) = \min\limits_{u_{k}} \mathbb{E}_{w_{k}} \bigg\{ g_{k}(x_{k},u_{k},w_{k}) + \alpha \phi_{k+1} (f_{k}(x_{k}, u_{k}, w_{k})) \bigg\}$

# 3. Multiplicative cost

**In the framework of the basic problem, consider the case where the cost has the multiplicative form:**

$$\mathbb{E}_{w_{k}} \bigg\{ g_{N}(x_{N})g_{N-1}(x_{N-1},u_{N-1},w_{N-1})...g_{0}(x_{0},u_{0},w_{0})\bigg\}$$

The primitives of the problem are the same as for the generic DP framework:

* $x_{k}$ - state at time $k$
* $u_{k}$ - control at time $k$ (a strategy)
* $w_{k}$ - uncertainty at time $k$, the realization of a random variable

The DP algorithm proceeds as follows:

**Step 1. Start with:**

$J_{N}(x_{N})= g_{N}(x_{N})$

**Step 2. Work backwards in time**

At time $i$, select the $u_{k}$ which minimizes the expected cost:

$$J_{k}(x_{k})= \min\limits_{{u_{k} \in U_{k}}} \mathbb{E}_{w_{k}} \bigg\{ g_{N}(x_{N}) \prod_{k=i}^{N-1} g_{k}(x_{k}, \mu_{k}(x_{k}), w_{k}) \bigg\}$$

And the optimal policy becomes the $\mu^{*}_{i},...,\mu^{*}_{N-1}$ which result from this optimizes.

$$J^{*}_{k}(x_{k}) = J_{k}(x_{k})$$

The policy which minimizes the expected cost is equivalent to a shortest path problem and thus satisfies the principal of optimality: the policies which optimize the tail subproblems are necessarily also a part of the optimal policy. Minimizing cost working backwards solves for the minimal cost.

# 4. Knapsack Problem

* *states:* $z_{i}$ weight left after adding item $i$ and previous items stored and amount
* *controls:* $u_{i}$ adding a weight $x_{i}w_{i}$

$$u_{i}(x_{i}) \in \{ 0 \leq u_{i} \geq z_{i}, z_{i} \in [0, Z] \}$$

* *uncertainty:* None

* *dynamics:* $f_{i}(x_{i}, u_{i}) = z_{i+1} = z_{i} - x_{i}w_{i}$

* *cost:* 
$$g_{i}(x_{i},u_{i}) = \frac{(z_{i} - x_{i}w_{i})}{w_{i}} v_{i}$$
The cost of not filling up the remaining space with that item.

**DP algorithm**
$$g_{N}(x_{N}) = J_{N}(x_{N}) = \frac{(z_{N} - x_{N}w_{N})}{w_{N}} v_{N}$$
Filling up the remaining space with the last item.

$$J_{i}(x_{i}) = \min\limits_{u_{i}}\bigg\{ g_{i}(x_{i},u_{i}) + J_{i+1}(f_{i}(x_{i}, u_{i}))\bigg\}$$


# 5. Traveling Repairman Problem.

* *states:* $x_{k}$ Sites served so far
* *controls:* $u_{k}$ Site to serve next

$$u_{k}(x_{k}) \in \big\{ s_{i-1}, s_{j+1}\big\}, x_{k} = \big\{ s_{i}, s_{i+1}, ..., s_{j}\big\}$$

* *uncertainty:* $w_{k}$ none

* *dynamics:* $f(x_{k},u_{k}) = x_{k} \cup \big\{u_{k}(x_{k})\big\}$

* *cost:*

$$g_{k}(x_{k},u_{k}) = t_{k} + \sum^{U_{k}} c_{i}$$

where $t_{k}$ is travelling cost from $u_{k-1}(x_{k-1})$ to $u_{k}(x_{k})$ and $c_{i}$ is the waiting cost of each site not yet visited.

$S$ is the set of all sites and $U_{k} = S - x_{k}$.

* *constraints:* Next site to serve must be adjacient to the sites served so far.

**DP algorithm**

$$g_{N}(x_{N}) = J_{N}(x_{N})$$

$$J_{k}(x_{k}) = \min\limits_{u_{k}}\bigg\{ g_{k}(x_{k},u_{k}) + J_{k+1}(f_{k}(x_{k}, u_{k}))\bigg\}$$



